// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHwkNe_Z7E00W5BbQvScS_haJ3ruvXHw',
    appId: '1:908367980514:android:9b7820a678e31b91cbbbbb',
    messagingSenderId: '908367980514',
    projectId: 'homeowners-b2f46',
    storageBucket: 'homeowners-b2f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2n6CWO6a6xJLVnsB9ML0WOAsaNydnIo',
    appId: '1:908367980514:ios:3753c68253d988e6cbbbbb',
    messagingSenderId: '908367980514',
    projectId: 'homeowners-b2f46',
    storageBucket: 'homeowners-b2f46.firebasestorage.app',
    iosBundleId: 'com.leosgroup.homeowners.homeowners',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKyTcgyY9s3p6xasJy1HFnnmDg73zZ9m8',
    appId: '1:908367980514:web:7a6809a6c2e1027ecbbbbb',
    messagingSenderId: '908367980514',
    projectId: 'homeowners-b2f46',
    authDomain: 'homeowners-b2f46.firebaseapp.com',
    storageBucket: 'homeowners-b2f46.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ2n6CWO6a6xJLVnsB9ML0WOAsaNydnIo',
    appId: '1:908367980514:ios:3753c68253d988e6cbbbbb',
    messagingSenderId: '908367980514',
    projectId: 'homeowners-b2f46',
    storageBucket: 'homeowners-b2f46.firebasestorage.app',
    iosBundleId: 'com.leosgroup.homeowners.homeowners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKyTcgyY9s3p6xasJy1HFnnmDg73zZ9m8',
    appId: '1:908367980514:web:38c465838b0d51ffcbbbbb',
    messagingSenderId: '908367980514',
    projectId: 'homeowners-b2f46',
    authDomain: 'homeowners-b2f46.firebaseapp.com',
    storageBucket: 'homeowners-b2f46.firebasestorage.app',
  );

}