// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4T5iJ56RfPg6OK6G8KP3J5vKOV6aEus',
    appId: '1:680289578611:android:c13ace8eb0fa95ec924406',
    messagingSenderId: '680289578611',
    projectId: 'homeowners-8f1f7',
    storageBucket: 'homeowners-8f1f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqK1Rie1VUwDqGEQ6lIErtpepnzwIwW8',
    appId: '1:680289578611:ios:c518aa4ebb97e693924406',
    messagingSenderId: '680289578611',
    projectId: 'homeowners-8f1f7',
    storageBucket: 'homeowners-8f1f7.firebasestorage.app',
    iosBundleId: 'com.leosgroup.homeowners.homeowners',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlHqokUNynXKa91cDbvvZxsVS0HwEfDKw',
    appId: '1:680289578611:web:c50532ec84918ff4924406',
    messagingSenderId: '680289578611',
    projectId: 'homeowners-8f1f7',
    authDomain: 'homeowners-8f1f7.firebaseapp.com',
    storageBucket: 'homeowners-8f1f7.firebasestorage.app',
  );

}